name: cicd udp app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write    # Required for OIDC
  contents: read     # Required to access repo

  
env:
    python_version: 3.11
    AWS_REGION: ${{ secrets.AWS_REGION }}  #us-east-1
    ECR_REPO: $ACCOUNT_ID.ECR.$AWS_REGION.amazonaws.com/$IMAGE_NAME
    ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
    IMAGE_NAME: portfolio25


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }} # or $python_version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run unit test
        run: pytest test.py
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build docker image #Prevent workflow from failing when no tests yet
        run: docker build -t riveluino86/portfolio25 .
         
      - name: list all s3 buckets
        run: aws s3 ls
